# Config for prime offloading and suspended gpu on idle
#
Section "ServerLayout"
    Identifier "layout"
    Option "AllowNVIDIAGPUScreens"
    Option "AutoBindGPU" "false" # Didn't work - lightdm restart needed on boot
EndSection

Section "Device"
    Identifier "nvidia"
    Driver "nvidia"
    BusID "PCI:1:0:0"
    Option "AllowEmptyInitialConfiguration"

EndSection

